### ISSUE TITLE
missing changelog in release note

### ISSUE THREAD

**Issue by raphaelauv** [apache/parquet-java#1381]
hi, releases on the parquet website -> https://parquet.apache.org/blog/2024/06/16/1.14.1/

are not showing the changes or a link to https://github.com/apache/parquet-java/blob/master/CHANGES.md?plain=1

**Comment by raphaelauv** [comment]
are still missing 1.14.2 , 1.14.3 , 1.14.4

**Comment by Fokko** [comment]
@raphaelauv Thanks for raising this. I'm seeing 1.14.2 and 1.14.3:

![image](https://github.com/user-attachments/assets/55ca8d14-6ca5-46d7-a599-29167d4137f2)

Can you maybe try clearing your cache? So we can figure out what's going on.

1.14.4 is staged for release: https://github.com/apache/parquet-site/pull/88
