### ISSUE TITLE
Make Parquet Hadoop 3 compatible

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2391]
It seems Hadoop 3 is getting more mature and the downstream projects and distros (e.g. Spark, CDP) are slowly transitioning to use it.
Since Hadoop 2 is probably the standard for a long term maybe we can just benefit of having an extra test configuration that provides the Hadoop 3.x dependencies to ensure that Parquet's current code base is 'forwards' compatible.

**Reporter**: [Ismaël Mejía](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iemejia) / @iemejia

<sub>**Note**: *This issue was originally created as [PARQUET-1697](https://issues.apache.org/jira/browse/PARQUET-1697). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by Fokko** [comment]
Closing this one, since we're at Hadoop 3.3.6 today 👍
