### ISSUE TITLE
Implement vectored IO in parquet file format

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2703]
We recently added a new feature called vectored IO in Hadoop for improving read performance for seek heavy readers. Spark Jobs and others which uses parquet will greatly benefit from this api. Details can be found here 

<https://github.com/apache/hadoop/commit/e1842b2a749d79cbdc15c524515b9eda64c339d5>

https://issues.apache.org/jira/browse/HADOOP-18103

https://issues.apache.org/jira/browse/HADOOP-11867

**Reporter**: [Mukund Thakur](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mthakur)
**Assignee**: [Steve Loughran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stevel@apache.org) / @steveloughran
#### Related issues:
- [Bump hadoop.version from 3.2.3 to 3.3.5](https://issues.apache.org/jira/browse/PARQUET-2277) (is blocked by)
- [High performance vectored read API in Hadoop](https://issues.apache.org/jira/browse/HADOOP-18103) (relates to)
- [Vectored Read into off-heap buffer broken in fallback implementation](https://issues.apache.org/jira/browse/HADOOP-19101) (is related to)
- [Vector IO: consistent specified rejection of overlapping ranges](https://issues.apache.org/jira/browse/HADOOP-19098) (is related to)
- [Improve Parquet IO Performance within cloud datalakes](https://issues.apache.org/jira/browse/PARQUET-2486) (is superceded by)
- [Utilize Hadoop vectorized APIs](https://issues.apache.org/jira/browse/SPARK-44116) (is depended upon by)
#### PRs and other links:
- [GitHub Pull Request #1103](https://github.com/apache/parquet-mr/pull/1103)
- [GitHub Pull Request #1139](https://github.com/apache/parquet-mr/pull/1139)
- [GitHub Pull Request #1330](https://github.com/apache/parquet-mr/pull/1330)

<sub>**Note**: *This issue was originally created as [PARQUET-2171](https://issues.apache.org/jira/browse/PARQUET-2171). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Mukund Thakur](https://issues.apache.org/jira/browse/PARQUET-2171?#comment-17578174):
CC [~stevel@apache.org]

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2171?#comment-17578470) / @theosib-amazon:
This might synergize well with the bulk I/O features I've been adding to ParquetMR. Some of the initial work is already in some PRs, and the rest of the plan can be found at <https://docs.google.com/document/d/1fBGpF_LgtfaeHnPD5CFEIpA2Ga_lTITmFdFIcO9Af-g/edit?usp=sharing>

I determined what to optimize from profiling, and I have run experiments on the new implementation. I glanced through your Hadoop commits, and I noticed that you use ByteBuffer a lot. I have found ByteBuffer to impose a nontrivial amount of overhead, and you might want to consider providing array-based methods as well.

**Comment by asfimport** [comment]
[Steve Loughran](https://issues.apache.org/jira/browse/PARQUET-2171?#comment-17578637) / @steveloughran:
> I have found ByteBuffer to impose a nontrivial amount of overhead, and you might want to consider providing array-based methods as well.


mixed feelings. its hard to work with but some libraries (parquet...) love it, which partly drove our use of it. if you use on heap buffers is just arrays with more hassle.

FwIW, i was looking at some of the parquet read code and concluding that the s3a FS should implement read(bytebyffer)  as a single vectored IO read. currently the base class implementation reads into a temp byte array and so breaks prefetching...the s3afs only sees the read(bytes) of the shorter array, not the full amount wanted

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2171?#comment-17579770) / @theosib-amazon:
The parquet reader has two phases of reading. One does the raw I/O and decompression. Someone is working on an asynchronous implementation of this, which should help a lot. The second phase works on the output of that, providing higher-level data types. My PRs improve on this by eliminating LittleEndianInputStream, which was super inefficient, plus some other improvements in the most critical paths. All of these improvements are incremental, of course, and we're happy to get contributions that improve on this further.

**Comment by asfimport** [comment]
[Steve Loughran](https://issues.apache.org/jira/browse/PARQUET-2171?#comment-17724339) / @steveloughran:
mukund, is there a PR up for this? even though it's not going to be merged, it needs to be shared for others to pick up

**Comment by asfimport** [comment]
[Mukund Thakur](https://issues.apache.org/jira/browse/PARQUET-2171?#comment-17724359):
Not yet Steve. I plan to do it soon.

**Comment by peter-toth** [comment]
@steveloughran, @mukund-thakur we noticed that when vectoried IO is enabled the `BytesRead` metrics of Spark tasks are not correct.
Spark fetches that metric via `FileSystem.getAllStatistics` see
- https://github.com/apache/spark/blob/5d491f62748b4b9c34bc3b5bd7390f7b5ca75053/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FileScanRDD.scala#L98-L109 and
- https://github.com/apache/spark/blob/5d491f62748b4b9c34bc3b5bd7390f7b5ca75053/core/src/main/scala/org/apache/spark/deploy/SparkHadoopUtil.scala#L164-L170

I wonder if this is a known issue?

**Comment by steveloughran** [comment]
file a hadoop s3a bug, it should be updating. do test with 3.4.3/3.5 and tell us which input stream option you are using. It may be the new prefetching stream which is now on by default.

the IOStatistics API is really the best way to collect stats as you get per input stream values (which is done in a thread context so you don't even need to get hold of the input stream itself). But we do try and promote the count of bytes read, so we should check stats updates there

**Comment by peter-toth** [comment]
I hit this issue in a local Spark test without S3. Opened a ticket here: https://issues.apache.org/jira/browse/HADOOP-19863
