### ISSUE TITLE
Invoking flush before closing the output stream in ParquetFileWriter

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2893]
It has been observed in customer deployments that sporadically it so happens that using Spark, an "Insert overwrite"  generates an Invalid / Corrupted Parquet  file. There are no exceptions and tasks writing, are committed successfully and shutdown is graceful, once all the tasks are done.

However when the written files are read data corruption occurs, which on analysis shows that "Expected 15356 uncompressed bytes but got 15108"

deficit of 248 bytes.

Given the low frequency of occurrence, suspicion is that output stream is closed before fully flushing the buffered the data.

So suggestion is to add a flush method, between writing footer and closing the stream, in the end() method of 

**org.apache.parquet.hadoop.ParquetFileWriter**

**Reporter**: [Asif](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ashahid7) / @ahshahid
**Assignee**: [Asif](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ashahid7) / @ahshahid
#### PRs and other links:
- [GitHub Pull Request #1309](https://github.com/apache/parquet-mr/pull/1309)

<sub>**Note**: *This issue was originally created as [PARQUET-2454](https://issues.apache.org/jira/browse/PARQUET-2454). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Asif](https://issues.apache.org/jira/browse/PARQUET-2454?#comment-17839927) / @ahshahid:
thanks `[~gangwu]`  for merging and reviewing!

**Comment by steveloughran** [comment]
this is somewhat problematic. s3a will complain about uses of hflush/hsync as it is generally a sign of code expecting these api calls to have some side effect.

@ahshahid now this is in -does the problem still exist?

**Comment by steveloughran** [comment]
calling flush() should suffice. hflush() says "block until all replications are synchronised" which is more expensive on HDFS; normal close() returns after one.

**Comment by ahshahid** [comment]
This issue was seen in customer's environment, after the change, had not
heard back since, so I presume its resolved.
Pls take a call as appropriate, regarding hflush/flush.. Though if I
remember correctly, the code path is hit during commit of data , so I used
hflush. ( & I must have borrowed its usage from somewhere else in the code).
