### ISSUE TITLE
Bump to Thrift 0.20.0

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2899]
**Reporter**: [Fokko Driesprong](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fokko) / @Fokko
**Assignee**: [Fokko Driesprong](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fokko) / @Fokko
#### PRs and other links:
- [GitHub Pull Request #1327](https://github.com/apache/parquet-mr/pull/1327)

<sub>**Note**: *This issue was originally created as [PARQUET-2462](https://issues.apache.org/jira/browse/PARQUET-2462). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by paliwalashish** [comment]
@Fokko The PR #1327 has been merged . Shall we close this issue?

**Comment by Fokko** [comment]
@paliwalashish Yes, thank you 👍
