### ISSUE TITLE
Adjust PR template to reference GitHub issue tracker

### ISSUE THREAD

**Issue by rok** [apache/parquet-java#2932]
Now that we moved issue tracking to GitHub we should adjust our pull request template.

**Comment by wgtmac** [comment]
I'm not sure it is a good idea to copy https://github.com/apache/arrow/blob/main/dev/merge_arrow_pr.py so we can automatically close related issue while merging PRs.

**Comment by rok** [comment]
I wonder if we could avoid the script and just use the merge button?
@raulcd Why is Arrow currently using the script instead of the button?

**Comment by raulcd** [comment]
The merge script still does several issues like, validate the milestone is set correctly, updating the Title name, authors, setting the correct lables if necessary.
We could investigate if some of those issues could be automated when merging with the merge button but the one I am not entirely sure how we would like to do is the milestone validation and setting we do before merging.

**Comment by rok** [comment]
That sounds like we probably don't want to use the merge button then.
For automated closing of connected issues after merges we could use [github automation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

**Comment by wgtmac** [comment]
> That sounds like we probably don't want to use the merge button then. For automated closing of connected issues after merges we could use [github automation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

Sounds good. There are always new stuffs to learn :)
