### ISSUE TITLE
Column/field description

### ISSUE THREAD

**Issue by simonaubertbd** [apache/parquet-java#2970]
### Describe the enhancement requested

Hello,

I may have misunderstood or misread the documentation but I didn't find it. I would love to have a field/column description just like we have in databases :

![image](https://github.com/user-attachments/assets/30b01b21-5b99-43e0-b125-c9eab7ffa033)

Best regards,

Simon

**Comment by wgtmac** [comment]
I don't think we have this kind of information in parquet: https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L414

**Comment by simonaubertbd** [comment]
@wgtmac Oooooh you're right, my bad. I post it on the bad githud repo (to my defense, that's where the parquet documentation points out). I close the issue for the moment.

Best regards,

Simon
