### ISSUE TITLE
Parquet 1.14.2-RC1 breaks compat with Avro 1.7, 1.8, 1.9

### ISSUE THREAD

**Issue by clairemcginty** [apache/parquet-java#2992]
### Describe the bug, including details regarding any error messages, version, and platform.

AvroSchemaConverter references Avro logical type converters that aren't available in Avro versions below 1.10: See more here: https://github.com/apache/parquet-java/pull/1115/files#r1721966099

For reference, these are the local TIMESTAMP converters available in Avro 1.10+: https://github.com/apache/avro/blob/release-1.10.0/lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java#L172-L194

Whereas in 1.9.2, only `timestampMillis`/`timestampMicros` area available: https://github.com/apache/avro/blob/release-1.9.2/lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java#L158-L168

### Component(s)

Avro

**Comment by wgtmac** [comment]
@Fokko Should we include this in the 1.14.2?

**Comment by Fokko** [comment]
@wgtmac Yes, looks like it 👍
